# Generated by Django 4.0.3 on 2022-09-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_url', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=100)),
                ('landmark', models.TextField(blank=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('total_docks', models.IntegerField()),
                ('bikes_availible', models.IntegerField()),
                ('dropoff_docks', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripePasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_stripeID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userhasbike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_bike', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_booking_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_charged', models.CharField(blank=True, max_length=255, null=True)),
                ('time_of_purchase', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeCustomerId', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('stripeSubscriptionId', models.CharField(blank=True, max_length=255, null=True)),
                ('cancel_at_day_end', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_postcode', models.CharField(max_length=20)),
                ('booking_from', models.TextField()),
                ('booking_to', models.TextField(blank=True, null=True)),
                ('has_pass', models.BooleanField(default=False)),
                ('booking_time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=False)),
                ('bicycle_drop_status', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
